var my_list = ({
  'الجامعه الاردنية':'https://chat.whatsapp.com/BxCoypLdiGB4gSDGRfojDz',
  'رغدان':'https://chat.whatsapp.com/JJRuLRpICUaGYeAO3Avhay',
  'الجاردنز':'https://chat.whatsapp.com/EJ0IgUUwdykEpRkTrxPJzg',
  'خلدا':'https://chat.whatsapp.com/CBKjNfoU1Fw0bdJJtPwBoh',
  'نزال':'https://chat.whatsapp.com/DbWZWpeE5REIN08S0qKNjd',
  'ماركا':'https://chat.whatsapp.com/KQ8AGUALcA43TOsEJPambH',
  'صويلح':'https://chat.whatsapp.com/K1fpluhCNAXAzyan1p9CbM',
  'طبربور':'https://chat.whatsapp.com/EoNMc39z0w19FRBtDlqIhE',
  'ضاحية الرشيد':'https://chat.whatsapp.com/JvRx9wOjoYNGEeidRAsCnm',
  'وادي السير':'https://chat.whatsapp.com/HUO3AWTtF29C19uwPHDTHT',
  'الهاشمي':'https://chat.whatsapp.com/LppJT9cpj5b5eVGUW13Zcb',
  'الزهور':'https://chat.whatsapp.com/Dy0FvDdFcxs4D9p5jX4qpW',
  'الوحدات والاشرفية':'https://chat.whatsapp.com/KBzwhgUC24jEZk9FPEE2rK',
  'القويسمة':'https://chat.whatsapp.com/Jwlbqstvbd3AuJON820G1p',
  'ابو علندا':'https://chat.whatsapp.com/EhvaFS1enBT7Ch8EnXhVmq',
  'الشرق الاوسط':'https://chat.whatsapp.com/CoFjpQW14DtELqXsTU41Lu',
  'سحاب':'https://chat.whatsapp.com/HZh5Jqedxud5PHFXt7VN6X',
  'البنيات والمقابلين':'https://chat.whatsapp.com/GwFblOCXLdqDv1Vv3KvpnK',
  'مرج الحمام':'https://chat.whatsapp.com/KQTrH38MtNX0ppaLm6D4dF',
  'ناعور':'https://chat.whatsapp.com/CeZlAb0oXi7KTOlsGdvrtM',
  'مادبا ام البرك':'https://chat.whatsapp.com/GtepyfJsn9rJiFwPj8O95P',
  'مادبا الروضة':'https://chat.whatsapp.com/G9M4uKfqsnGCLZF0PgwE2a',
  'مادبا غربي':'https://chat.whatsapp.com/HzggOg2lmKuApsyotOJK0Y',
  'مادبا شرقي':'https://chat.whatsapp.com/Jsshz2Na67Z7UkeWmiCPBW',
  'الدوار الثاني':'https://chat.whatsapp.com/IeosSBlzrrM0Ql8wiF2L9i',
  'العبدلي':'https://chat.whatsapp.com/GpydUzTb3HrGXIGof7lI8u',
  'النزهة':'https://chat.whatsapp.com/KBwvOb4X9pp1AcOILjcxpw',
  'البقعة':'https://chat.whatsapp.com/JOAAuKJ6mV13fRCOc01qiJ',
  'ابو نصير':'https://chat.whatsapp.com/HhBv13JPnLyDjbXR00uhLw',
  'الزرقاء':'https://chat.whatsapp.com/IPjKeU27zHB1AcjYcqc4eU',
});